const Map<String, String> bnBD = {
  'app_name': 'এক্সপেন্স ট্র্যাকার',
  'home': 'হোম',
  'sparkle': 'স্পার্কল',
  'sparkle_insights': 'স্পার্কল ইনসাইটস',
  'profile': 'প্রোফাইল',
  'logout': 'লগআউট',
  'login': 'লগ ইন',
  'signup': 'সাইন আপ',
  'email': 'ইমেইল',
  'password': 'পাসওয়ার্ড',
  'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
  'full_name': 'সম্পূর্ণ নাম',
  'enter_email': 'আপনার ইমেইল লিখুন',
  'enter_password': 'আপনার পাসওয়ার্ড লিখুন',
  'enter_name': 'আপনার নাম লিখুন',
  'confirm_your_password': 'আপনার পাসওয়ার্ড নিশ্চিত করুন',
  'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
  'dont_have_account': "অ্যাকাউন্ট নেই? ",
  'already_have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে? ',
  'welcome_back': 'স্বাগতম',
  'login_subtitle': 'আপনার ড্যাশবোর্ডে প্রবেশ করতে লগ ইন করুন',
  'create_account': 'অ্যাকাউন্ট তৈরি করুন',
  'signup_subtitle': 'বাজেট সহজে পরিচালনা করতে আমাদের সাথে যুক্ত হন',
  'good_morning': 'শুভ সকাল,',
  'no_profile_data': 'কোনো প্রোফাইল ডেটা লোড করা হয়নি',
  'retry': 'পুনরায় চেষ্টা করুন',
  'user_id': 'ব্যবহারকারী আইডি: @id',
  'today': 'আজ',
  'weekly': 'সাপ্তাহিক',
  'monthly': 'মাসিক',
  'income': 'আয়',
  'expense': 'ব্যয়',
  'balance': 'মোট ব্যালেন্স',
  'add_transaction': 'লেনদেন যোগ করুন',
  'title': 'শিরোনাম',
  'amount': 'পরিমাণ',
  'date': 'তারিখ',
  'select_type': 'ধরণ নির্বাচন করুন',
  'save': 'সংরক্ষণ করুন',
  'age': 'বয়স',
  'enter_age': 'আপনার বয়স লিখুন',
  'overall': 'সামগ্রিক',
  'history_of_today': 'আজকের ইতিহাস',
  'overall_history': 'সামগ্রিক ইতিহাস',
  'no_transactions': 'কোনো লেনদেন পাওয়া যায়নি',
  'today_balance': 'আজকের ব্যালেন্স',
  'overall_balance': 'সামগ্রিক ব্যালেন্স',
  'enter_title': 'শিরোনাম লিখুন (যেমন: স্টারবাক্স)',
  'enter_amount': 'পরিমাণ লিখুন (যেমন: ৪৫,৫০)',
  'select_date': 'তারিখ নির্বাচন করুন',
  'type': 'ধরণ',
  'amount_hint': 'পরিমাণ লিখুন',
};
