const Map<String, String> enUS = {
  'app_name': 'ExpenseTracker',
  'home': 'Home',
  'sparkle': 'Sparkle',
  'sparkle_insights': 'Sparkle Insights',
  'profile': 'Profile',
  'logout': 'Logout',
  'login': 'Log In',
  'signup': 'Sign Up',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'full_name': 'Full Name',
  'enter_email': 'Enter your email',
  'enter_password': 'Enter your password',
  'enter_name': 'Enter your name',
  'confirm_your_password': 'Confirm your password',
  'forgot_password': 'Forgot Password?',
  'dont_have_account': "Don't have an account? ",
  'already_have_account': 'Already have an account? ',
  'welcome_back': 'Welcome Back',
  'login_subtitle': 'Log in to track and optimize your expenses',
  'create_account': 'Create Account',
  'signup_subtitle': 'Join us to manage your budget easily',
  'good_morning': 'Good morning,',
  'no_profile_data': 'No profile data loaded',
  'retry': 'Retry',
  'user_id': 'User ID: @id',
  'today': 'Today',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'income': 'Income',
  'expense': 'Expense',
  'balance': 'Total Balance',
  'add_transaction': 'Add Transaction',
  'title': 'Title',
  'amount': 'Amount',
  'date': 'Date',
  'select_type': 'Select Type',
  'save': 'Save',
  'age': 'Age',
  'enter_age': 'Enter your age',
  'overall': 'Overall',
  'history_of_today': 'History of Today',
  'overall_history': 'Overall History',
  'no_transactions': 'No transactions found',
  'today_balance': 'CURRENT DAY BALANCE',
  'overall_balance': 'OVERALL BALANCE',
  'enter_title': 'Enter title (e.g. Starbucks)',
  'enter_amount': 'Enter amount (e.g. 45,50)',
  'select_date': 'Select date',
  'type': 'Type',
  'amount_hint': 'Enter amount',
};
